---
title: "<center>**Working with raster to stars in R**</center>"
author: "<center>Wyclife Agumba Oluoch (wyclifeoluoch@gmail.com) </center>"
date: "<center>`r Sys.time()`</center>"
bibliography: 
  - bib/packages.bib
nocite: '@*'
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
packages <- c("base",
              'knitr',
              'rmarkdown',
              'raster',
              'stars',
              'sf')
installed_packages <- packages %in% rownames(installed.packages())
if(any(installed_packages == FALSE)){
  install.packages(packages[!installed_packages])
}
lapply(packages, library, character.only = TRUE) |> invisible()
```

```{r write_bib, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
knitr::write_bib(c(
  .packages(), packages
), 'bib/packages.bib')
```

# **Create raster**

1.  This is one of the most **interesting** bits of the [*rmarkdown.*]{.ul} Kind of **Literate Programming.**

```{r}
r <- raster(ncols = 20, nrows = 20)
```

# **Fill raster**

```{r}
r[] <- round(rnorm(n = ncell(r)), 2)
```

# **Plot raster**

```{r}
plot(r)
```

# **Convert raster to stars**

```{r}
s <- st_as_stars(r) # This converts
```

# **Plot stars**

```{r}
plot(s)
```

# **Show pixel values**

```{r}
plot(s, text_values = TRUE, 
     col = terrain.colors(10, alpha = 1), 
     breaks = "equal")
```

# **References**
